# Generated by `infrataster init`
require 'infrataster/rspec'
require 'infrataster-plugin-firewall'

ENV['VAGRANT_CWD'] = File.dirname(__FILE__)

Infrataster::Server.define(
  :client_jp,
  '192.168.101.0/24',
  vagrant: true,
)

Infrataster::Server.define(
  :gw_jp,
  '172.16.1.0/24',
  vagrant: true,
)

Infrataster::Server.define(
  :gw_uk,
  '172.16.2.0/24',
  vagrant: true,
)

Infrataster::Server.define(
  :client_uk,
  '192.168.102.0/24',
  vagrant: true,
)

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.order = 'random'
end
